---
title: "1D-Discrete Dynamical Systems (Assignment Sheet 1)"
subtitle: "Introduction to Chaos Applied to Systems, Processes, and Products (ETSIDI, UPM)"
author: "Alfonso Allen-Perkins, Juan Carlos Bueno, and Eduardo Faleiro"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    toc: true
    toc_float: true
  pdf_document:
    toc: true
---
## Exercise 1

Consider the map:

$$ x_{n+1} = \cos(x_n) $$

- Plot several orbits (\( x_n \) vs \( n \)) starting from the interval \( [-\pi, \pi] \).
- Create a **cobweb** plot (\( x_{n+1} \) vs \( x_n \)) and identify the fixed points.

---

## Exercise 2

For each of the following maps, generate a **cobweb plot** starting from an appropriate initial condition \( x_1 \):

- \( x_{n+1} = x_n^2 \) for \( x_1 \) in \( [-1,1] \).
- \( x_{n+1} = 3x_n - x_n^3 \) for \( x_1 \) in \( [-2,2] \) and also for \( x_1 = 2.1 \).
- \( x_{n+1} = e^{-x_n} \) for \( x_1 \) in \( [0,1] \).

---

## Exercise 3

Consider the simple linear map:

$$ x_{n+1} = \mu \cdot x_n $$

- Find the **fixed points** and analyze their **nature** based on the value of \( \mu \).
-  Extend this analysis to study the fixed points of the generic nonlinear map:

  $$ x_{n+1} = g(x_n, \mu) $$

---

## Exercise 4

Analyze the stability of the fixed points for the maps given in **Exercise 2**.

---

## Exercise 5

The logistic map:

$$ x_{n+1} = \mu \cdot x_n (1 - x_n) $$

is a **paradigm of chaos** in the domain \( [0,1] \).

- Identify the fixed points.
- Generate cobweb plots for the following values of \( \mu : 2.0, 2.5, 3.0, 3.5, 3.7, 4.0 \).

---

## Exercise 6

Plot the **bifurcation diagrams** for the following maps:

1. \( x_{n+1} = \mu \sin(x_n) \).
2. \( x_{n+1} = 3x_n - x_n^3 \).
3. \( x_{n+1} = e^{ -\mu (1 - x_n) } \).
4. \( x_{n+1} = \mu \cdot x_n (1 - x_n) \) for \( \mu \) in \( [2,4] \).
5. \( x_{n+1} = \mu \frac{x_n^2}{1 + x_n^2} \).
6. \( x_{n+1} = \mu \cdot x_n + x_n^3 - x_n^5 \) for \( \mu \) in \( [-2,2] \).

---

::: {.info}
**Note:** Ensure that your plots use sufficient iterations to observe long-term behavior.
:::